### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Good-player** [DistrictOfJoban/Joban-Client-Mod#12]
### Describe the Bug

Crashed
with code 1

### Reproduce

1.turn Minecraft launcher
2.Run Forge 1.20.1-forge-47.1.0
3.Crash

### Expected Result

Just WORK

### Modloader

Minecraft Forge

### Minecraft Version

1.20.1

### JCM Version

2.0.0 beta

### MTR Version

MTR-forge-1.20.1-3.2.2-hotfix-2

### Operating System

Mac OS Sonoma 14.3.1

**Comment by Kenny-Hui** [comment]
Exit Code 1 is not helpful at all, please attach the log found in `.minecraft/logs/latest.log`
I'll keep this closed until further information can be supplied, as it's not quite possible to debug based on the limited information.

**Comment by Good-player** [comment]
> 退出代码 1 根本没有帮助，请附上在`.minecraft/logs/latest.log` 我会保持此关闭直到可以提供更多信息的日志，因为基于有限的信息无法进行调试。

k

**Comment by Good-player** [comment]
> Exit Code 1 is not helpful at all, please attach the log found in `.minecraft/logs/latest.log` I'll keep this closed until further information can be supplied, as it's not quite possible to debug based on the limited information.

Im done
Check the issue again

**Comment by Kenny-Hui** [comment]
JCM v2.0.0 Beta is not compatible with MTR 3.2.2
Please stay on JCM v1.2.2 for the time being, or update to MTR 4.0 beta (But please make sure you have backup before updating MTR 4)

**Comment by Good-player** [comment]
Thanks You!
