### ISSUE TITLE
[Bug] Non-CJK Rendering Broken in PIDS

### ISSUE THREAD

**Issue by Hedgehog-Aviation** [DistrictOfJoban/Joban-Client-Mod#17]
### Describe the Bug

In the MTR config settings, I have my text rendering set to Non-CJK only (English characters only) and it works in MTR PIDS Blocks. But in Joban Client PIDS blocks, it still shows both English and Chinese/Korean (sorry not sure) characters. Back in MTR V3 and Joban V1, this did not happen. 

### Reproduce

1. Make a simple railway and make a station with a Joban Client PIDS
2. Go to the MTR config and set text rendering to NON-CJK only
3. Watch as the PIDS still shows CJK characters

### Expected Result

I expect the PIDS to only show English Characters

### Modloader

Fabric

### Minecraft Version

1.20.4

### JCM Version

2.0.0 beta 3

### MTR Version

4.0.0 beta 9

### Operating System

Windows 10

### Crash Report or Log

No crash, but log is here:

https://mclo.gs/79ym51C

### Extra Informations

This is running on an Aternos server, but I don't think this affects it.

**Comment by Kenny-Hui** [comment]
The PIDS both in MTR Mod and JCM never followed the language display settings.
What I suspect is that your station name only has English. In JCM v1 they would follow the available languages in destination, while in JCM v2, the ETA is independent from the destination string, and would cycle regardless.

It's certainly something worth thinking about, maybe rethinking how the entire PIDS customization thing should be done as a whole.

**Comment by Hedgehog-Aviation** [comment]
Thank you for your answer, that would definitely make sense. It would be
nice to have a way to change the ETA text as well.
Love the MTR mod. :)
