### ISSUE TITLE
[Suggestions] pids customisation

### ISSUE THREAD

**Issue by 888845** [DistrictOfJoban/Joban-Client-Mod#19]
### Suggestion Type

PIDS Preset

### Suggestion

add more presets and make customisation like the mtr lets play server where the pids are mostly custom. make it in the game instead of mod files
![2024-10-23_16 56 00](https://github.com/user-attachments/assets/c451660f-7554-4d73-a88b-d18baa9a65a7)

### Implementation Details/References

dosent matter as long as it isn't complex

**Comment by Kenny-Hui** [comment]
In-game editor is too much effort. Unfortunately it's *really* hard to satisfy everyone's requirement around the world.
