### ISSUE TITLE
Text not showning in the config screen.

### ISSUE THREAD

**Issue by CokeStudios** [DistrictOfJoban/Joban-Client-Mod#6]
### Describe the Bug

Text not showning in the config screen.

### Reproduce

open the config scrren

### Expected Result

Should show

### Modloader

Fabric

### Minecraft Version

1.20.4

### JCM Version

2.0.0-beta (newest from Actions)

### MTR Version

4.0.0 beta 7 (newest from Actions)

### Operating System

MacOS 11

### Crash Report or Log

no error in the log

**Comment by CokeStudios** [comment]
<img width="1280" alt="截屏2024-05-28 下午7 52 11" src="https://github.com/DistrictOfJoban/Joban-Client-Mod/assets/89446485/92e41949-5010-405d-b193-dd3bdf136f77">

**Comment by CokeStudios** [comment]
<img width="1280" alt="截屏2024-05-28 下午8 01 37" src="https://github.com/DistrictOfJoban/Joban-Client-Mod/assets/89446485/14bf9328-0796-4a84-86db-45b429f88f07">

**Comment by Kenny-Hui** [comment]
Please try and see if the latest action build is better, I don't have access to a Mac so I can't test this

**Comment by CokeStudios** [comment]
yeah it's fixed
